sudo: required
language: go

services:
  - docker

env:
  - PORT=8080

go:
  - 1.13.x
  - tip

addons:
  chrome: stable

before_install:
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh
  # login to docker registries (dockerhub + heroku)
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - echo "$HEROKU_PASSWORD" | docker login -u "$HEROKU_USERNAME" --password-stdin registry.heroku.com

install:
  - go get github.com/agnivade/wasmbrowsertest
  - go get github.com/stretchr/testify/assert
  - mv $GOPATH/bin/wasmbrowsertest $GOPATH/bin/go_js_wasm_exec
  - export PATH=$GOPATH/bin:$PATH

script:
  - gofmt -l -s -w .
  - GOOS=js GOARCH=wasm go test ./... -v
  - docker build -t aarushik93/my-go-webcam .
  - docker tag aarushik93/my-go-webcam registry.heroku.com/$HEROKU_APP_NAME/web

deploy:
  provider: script
  script:
    # push to dockerhub
    docker push aarushik93/my-go-webcam;
    docker push registry.heroku.com/$HEROKU_APP_NAME/web;
  branch: master

after_success:
  - heroku container:login
  - heroku container:release web --app $HEROKU_APP_NAME


